<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagerBackendTest.ViewModels\TaskManagerBackendTest.ViewModels.csproj" />
    <ProjectReference Include="..\TaskManagerTest.Models\TaskManagerBackendTest.Models.csproj" />
  </ItemGroup>

</Project>
